syntax = "proto3";

package proto.renderprotocol.api.v1;

import "proto/renderprotocol/api/v1/rp_api_platform.proto";

option cc_enable_arenas = true;
option java_package = "com.nukive.renderprotocol.api.v1";
option objc_class_prefix = "";
option optimize_for = SPEED;
option swift_prefix = "";

message RPAppMetadata {
  string bundle_id = 1;
  string app_version = 2;
  RPPlatform platform = 3;
  string locale = 4;
  string sdk_version = 5;
}

message RPDeviceMetadata {
  string device_model = 1;
  string os_version = 2;
  RPPlatform platform = 3;
  optional float screen_width = 4;
  optional float screen_height = 5;
  optional float screen_density = 6;
}

message RPApiMetadata {
  RPAppMetadata app_metadata = 1;
  RPDeviceMetadata device_metadata = 2;
}

message RPSessionContext {
  string session_token = 1;
  optional string trace_id = 2;
  optional string locale_override = 3;
}
